### ISSUE TITLE
Feature request: Fliqlo missing features

### ISSUE THREAD

**Issue by jurczewski** [phaselden/FlipIt#1]
Hi, big fan of your project. Now when Flash is dead and a new version of Fliqlo is far from perfect, your project is a real helper.

If you plan to continue to develop this project I would suggest following features:
- AM/PM vs 24h toggle
- Font size picker
- Multi-monitor, but as a mirror of primary monitor. (The same clock on every monitor)

Have a good day :-)

**Comment by SnailMango** [comment]
Hi! Replying to say that I'd love the features suggested from @jurczewski too! Also it would be nice to be able to resize the main clock and use it on the primary monitor only. I'm using DisplayFusion to manage my screensaver, but timezones appear on the secondary monitor (vertical in my case) even if I disable the screensaver on that monitor.
![Immagine](https://user-images.githubusercontent.com/64862343/104491689-e2b5f200-55d2-11eb-8ba6-d4d82b837a58.jpg)

**Comment by phaselden** [comment]
Thanks for the feedback. I plan to look into these on the weekend.

**Comment by mldu859** [comment]
Love this as an alternative to fliqlo as well! Hope you keep working on it. As others have said, font size picker and multi monitor support would be amazing. Mirroring the clock to another monitor would be great. Thanks for making this and keep up the great work!

**Comment by fluoroom** [comment]
I love this project! I'd like mirroring the main clock on two monitors too or maybe entering my own cities would be nice.

**Comment by ronilaukkarinen** [comment]
Fliqlo finally stopped working here as well so this is great.

However we don't use AM and PM in Finland at all so 24h at least is a must.

Thanks so far!

**Comment by Cris--** [comment]
Also the new release without flash from the original Fliqlo author needs internet access to work. That is a no go i think! Doesn't matter which resources it needs! Thanks for this alternative and hope also for a new version here with some more already described features!

**Comment by phaselden** [comment]
Thanks @Cris--, that's good to know as I was considering automating the download of fonts from Google and also periodically updating timezone information via the net.

**Comment by chasingwatts** [comment]
@phaselden Hi Phil, I didn't see your email anywhere, so I'll post here.  First, great project - really like this screen saver.  I downloaded your source and made some of the updates here (and what I wanted).  Let me know if you want my source - happy to share so you can review and merge in if you like?

![flipit-city](https://user-images.githubusercontent.com/42514460/104933243-4c852180-596e-11eb-904c-fea61e88e465.png)
![flipit-settings](https://user-images.githubusercontent.com/42514460/104933245-4d1db800-596e-11eb-93cf-d1c8d75e6443.png)
![flipit-mirror](https://user-images.githubusercontent.com/42514460/104933246-4d1db800-596e-11eb-8c28-28fcfd2d683f.png)

**Comment by zbt1** [comment]
Hi everyone,

I'm sorry for spamming, and it's not a valuable contribution but I just wanted to say that I love you all for putting that much effort into this amazing project!

**Comment by phaselden** [comment]
Hi @chasingwatts. Wow - great work. It's a bit different from the stuff I have underway but I may be able to use parts of your changes. Feel free to email me what you have at phaselden at gmail dot com.

**Comment by phaselden** [comment]
A beta version of 1.2 is now available in the Releases

**Comment by phaselden** [comment]
A new beta build of 1.2 is now available. This one uses an embedded font which is closer (identical?) to the font used by Fliqlo. 
A known issue ATM is that the time displays smaller when used for the Current Time.

**Comment by phaselden** [comment]
No, just replace the .scr file. Note: Your settings from beta 1 will be lost, so it will default to its, er, default state. 

Also, I have had a report of the latest beta not working, so you might like to keep a copy of beta 1 in case you want to revert to that.

**Comment by redburn** [comment]
Thanks for your efforts @phaselden and @chasingwatts!

Too minor a thing to make a separate issue of, but perhaps the gray area behind the digits can be just a little bit lighter? It's almost invisible on my screen.

**Comment by phaselden** [comment]
Beta 3 is now available in the Releases page.

**Comment by phaselden** [comment]
Beta 4 is now available from the Releases page

**Comment by phaselden** [comment]
Version 1.2 has been released

I plan to close this ticket soon. Please create a new ticket for:
* Each feature request in this ticket which has not been implemented yet
* Other features requests. (one per ticket)
* Any new issues you find with 1.2

**Comment by jurczewski** [comment]
Hi. 
Glad to hear that! 
Can you include the .src file?
![image](https://user-images.githubusercontent.com/24575781/105980079-b9966680-6094-11eb-83a3-4630e1a45d6d.png)

**Comment by redburn** [comment]
@jurczewski Check again, it's there now.

**Comment by jurczewski** [comment]
Nevermind, I can see it has been updated 😀

**Comment by iostream047** [comment]
Dear sir, 
Thank you so much for this beautiful screensaver. The only issue I have is that in my world-clock view, where I have 3 cities right now, the day of the week is displayed for only one of them. Also, the city with the day displayed is one day ahead of the other two- this city is past midnight and its Tuesday for there. The "Monday" for the other two of my cities is not being displayed.
I am using v1.3. My request is to include a feature to "Show day of the week" that shows the day of the week for every city in  the list, individually, which I plan to always leave toggled on!
Thanks.
