### ISSUE TITLE
Feature request: disable asterisk that denotes time adjusted for Daylight Savings Time

### ISSUE THREAD

**Issue by explor202** [phaselden/FlipIt#10]
Some cities (Santiago, Adelaide, etc.) have an asterisk next to their time indicating the time displayed has been adjusted for DST. Can an option be added to disable the asterisk?

**Comment by explor202** [comment]
This could probably be closed. I used your edit workaround so Santiago no longer displays an asterisk next to the time.

**Comment by phaselden** [comment]
I actually like the idea, so let's not close it just yet and we'll see how much support it gets. 

On a related note, I was wondering about having an option of showing a + or - instead of the day if the city's time is for the next or previous day. If you have an opinion on that, let me know.

**Comment by explor202** [comment]
Personally I like seeing the day. I have added cities that have time zone three hours apart starting with mine. So as the day progresses, so does the day displayed for each city.

**Comment by explor202** [comment]
The option to enable/disable the asterisk works great Phil, thank you!
