### ISSUE TITLE
Feature request: Close on mouse move

### ISSUE THREAD

**Issue by SmilerRyan** [phaselden/FlipIt#12]
Unlike the old/standard [Fliqlo](http://fliqlo.com/) project, this is a great project.
I would like the option to have it close on mouse movement, as well as just by click or keypress.
Preferably, I would think this option should be enabled by default as most screensavers close on movement.

**Comment by redburn** [comment]
It does for me. Exit on mouse movement, that is.

**Comment by explor202** [comment]
My mouse has a built in sleep feature, so depending on how long my mouse has been inactive I may have to click one of it's buttons to wake it up first. But either way mouse movement closes the screensaver for me too.

**Comment by SmilerRyan** [comment]
I have the screensaver automatically start after 3 minutes, and my mouse does not go to sleep.
After re-checking, it only seems to close if I continue to move the mouse for over a second. Is this an intended feature?

**Comment by explor202** [comment]
Sounds like an issue with your mouse or maybe pointer speed settings. If my mouse isn't asleep, the screensaver closes with the slightest bit of movement of it.

**Comment by SmilerRyan** [comment]
I believe I have average mouse settings, it only seems to close quickly if I move it agressively.
I have attached my mouse speed settings below, along with the example speed.

![Mouse](https://user-images.githubusercontent.com/14893385/106824617-1dafc080-667b-11eb-97e6-0055b122b9d4.gif)

**Comment by SmilerRyan** [comment]
After checking the movement event, I have discovered that it does check if it has moved such a distance.
Removing the check closed the program as soon as it started (the mouse moved 0 pixels).
Lowering it from 5 to a lower number (like 2) did not help, but 0 did fixed my problem.

I will make a pull request with the change now, and I hope this helps others who experience the same issue as me.
![image](https://user-images.githubusercontent.com/14893385/106828649-88b0c580-6682-11eb-848a-b4485b6bf3e0.png)
