### ISSUE TITLE
Blank preview in settings

### ISSUE THREAD

**Issue by Lyapsus** [phaselden/FlipIt#19]
Instead of thousand words
![1](https://user-images.githubusercontent.com/37628546/110018323-77151900-7d27-11eb-9b1c-f88623e06255.png)

Windows' part and screensaver itself seem to work just fine, thanks for your work
![2](https://user-images.githubusercontent.com/37628546/110018507-a3309a00-7d27-11eb-9a2d-a1b3ca31b703.png)

**Comment by phaselden** [comment]
Hi @Lyapsus. 

Thanks for your post.

While I am not exactly sure, I think you might be referring to the large box in the top screenshot? If you select the World Times radio button, that box is enabled and is used to configure the cities that you want displayed on your World Times board. If you don't add any cities, a default set is displayed.

I can see how that might be confusing though and will try to think of a way to make it clearer.

**Comment by Lyapsus** [comment]
Oh I'm so dumb haha. All right then, thanks again for your creation.
Dunno if you prefer to leave it open not to forget so I'll better leave it as is.
