### ISSUE TITLE
Monitor not Working

### ISSUE THREAD

**Issue by VincentGaoHJ** [phaselden/FlipIt#22]
Hi Flipit Dev,

I am trying to use Flipit on my Win 10 Laptop, and it works properly when no other monitor is connected but stops popping up when I connect one to the laptop,

My monitor is 34-inch, 3440×1440 resolution, and 144Hz.

Any ideas on how to fix this?

**Comment by phaselden** [comment]
Hmm. Not sure what is going on there. Have you tried configuring the screen saver while the 2nd monitor is attached? I am wondering whether it considers the newly attached monitor to be monitor 1 and the (original) laptop monitor to be monitor 2, and is getting confused.

**Comment by VincentGaoHJ** [comment]
Sorry about the unclear description. This problem is nothing to do with Flipit. The genuine reason that caused it is that I connected a speaker along with the monitor, and its default human interface device seems to prevent the screen saver from popping up.
