### ISSUE TITLE
Screens revert to "Nothing"

### ISSUE THREAD

**Issue by mortydiego** [phaselden/FlipIt#25]
Hi!

I am not sure when this started happening (though I can tell you it was when I swapped over to a new laptop with Windows 10 in of June. Was, previously, on Windows 8.1), but every now and then the Screens settings revert back to "Nothing". 

Let me know what other information you need to investigate. Otherwise, I'm going to closely pay attention if this happens when I plug in the power [to the laptop], and/or if this happens after the laptop comes out of Sleep (I despise Windows' Sleep for many, many reasons), and/or if this happens after a reboot, etc...

I have the laptop docked to two external monitors, and the laptop's main screen is disabled.

Is anything else experiencing this?

Totally love this screensaver!

**Comment by phaselden** [comment]
Thanks for reporting this. I haven't heard of this one before. If you find any more information, please let us know.

**Comment by mortydiego** [comment]
Well, I thought I was on to something, but I am back to square one: wondering what the issue could be.

To get you up to speed...

The laptop, as a standalone (not docked) works perfectly fine, regardless of what the power settings are.

With the laptop docked, and thinking there is something about the laptop coming out of sleep then immediately disabling its screen and then ultimately projecting onto the two external monitors, meaning I now have three (3) screens in total (laptop screen and the two external), FlipIt kept one of the external screens at either Current or World time (depending on how I had it set up) once it came out of Sleep. However, today, all three screens reverted back to Nothing once the laptop was taken out of Sleep.

So, I am not quite sure what it could be.

The native screen savers seem to work fine, but there's really no other settings to them. Well, except for Photos (hmm).

**Comment by mortydiego** [comment]
So, I continued to keep the laptop screen enabled, yet, docked to the two external monitors.

I really thing this _may_ be a Windows thing, where it keeps its settings for the native monitor, i.e., the laptop monitor, but then loses any settings when projecting to the external monitors.

I did some looking up for a completely unrelated topic weeks ago, regarding apps repositioning themselves on external monitors when opening them up, for example, Chrome resizing itself to be smaller or bigger and on the left when it was last closed on the right side of the monitor. There was enough stink to it, that Microsoft is actually releasing a fix for it in an update coming out in October. I bring this up because I wonder if there is a relation to apps losing it's settings when being projected to external monitors. If that is the case, you can (or I can, I suppose) to close this issue.

**Comment by phaselden** [comment]
Your comment about "disabling its own screen" is interesting. Can you describe exactly how you configured it to do that?

From memory, writing and reading of the settings _should_ be forgiving enough to deal with monitors changing, but I am not sure I ever tested for the main monitor disappearing. I can imagine that if FlipIt asks the OS for information about monitors and it can't map what the OS returns to what is in the settings, then it might not behave as well as it might.

**Comment by mortydiego** [comment]
Yes! So, when you navigate to the Display settings (specifically) in Windows, when you click on the monitor in question and scroll down to Multiple Displays, you can choose what you want the monitor to present, or disconnect it.

To note, my laptop is Screen 1

![display settings 01](https://user-images.githubusercontent.com/89232456/131900681-3ac2e268-6edd-4cec-9209-7a69001c91f4.png)
![display settings 02](https://user-images.githubusercontent.com/89232456/131900713-4c6be7e6-56f9-4932-8a71-3abfb578c498.png)
![display settings 03](https://user-images.githubusercontent.com/89232456/131900725-577a127d-6ec7-450d-91ef-6a83ce6079ed.png)

In the last couple of days of having my laptop screen set as Extend Desktop to this Display, the Current time has been flipping back and forth between Display 2 and 3, where I initially set up both external monitors (2 and 3) as World Times. It's so weird!

**Comment by liucin** [comment]
![image](https://user-images.githubusercontent.com/44336209/142984536-2fb35b26-163f-462a-8f5c-29eeeea00069.png)
actually, you could check this out.

**Comment by mortydiego** [comment]
Thank you, @liucin 

I am thinking of closing this "issue", which I believe Windows, itself, is the culprit.

Reasoning for that is because I noticed when I set the screen saver to one of the native screen savers [that come with Windows], sometimes the screen saver settings is set to "NONE" when coming out of Sleep. So, it looks like Windows does not remember anything, and not just from the screen saver settings, but Windows will resize my active windows and relocate them to a different monitor. If you Google that issue - windows resizing and relocating - you will see this is a huge annoyance among Windows users with multiple monitors, such as I.

Again, thank you @liucin, thank you @phaselden

**Comment by liucin** [comment]
It seems that your issue is a knotty problem which I haven't met yet. It's a pity that my solution can't help.

---Original---
From: ***@***.***&gt;
Date: Sat, Nov 27, 2021 03:08 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [phaselden/FlipIt] Screens revert to "Nothing" (#25)




 
Thank you, @liucin
 
I am thinking of closing this "issue", which I believe Windows, itself, is the culprit.
 
Reasoning for that is because I noticed when I set the screen saver to one of the native screen savers [that come with Windows], sometimes the screen saver settings is set to "NONE" when coming out of Sleep. So, it looks like Windows does not remember anything, and not just from the screen saver settings, but Windows will resize my active windows and relocate them to a different monitor. If you Google that issue - windows resizing and relocating - you will see this is a huge annoyance among Windows users with multiple monitors, such as I.
 
Again, thank you @liucin, thank you @phaselden
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mortydiego** [comment]
@liucin You may not have come across this issue because it looks like you are only using one monitor. 

I believe the issue is with Windows and now it deals or not deals with external monitors. To recap, I have two (2) external monitors connected to my laptop. With that, it seems there is an issue with Windows going into SLEEP mode and that it acts as if it disconnects from the external monitors, then when Windows comes out of SLEEP mode, it reconnects to the monitors, but as if they are connected for the first time, therefore, when I open my active windows again, they are resized and relocated, i.e., they are not in the same place before SLEEP.

To say all that, I think this Windows issue also impacts the Screen Saver settings the same way - it doesn't remember that there are/were external monitors, so it reverts to NOTHING, and thus I would have to set up the settings, again.
