### ISSUE TITLE
Can't add India Standard Time

### ISSUE THREAD

**Issue by alexjamesbrown** [phaselden/FlipIt#29]
I've got colleagues in Delhi, and I can't seem to add India Standard Time / Delhi -
It's just not found in the list?

![image](https://user-images.githubusercontent.com/437743/133127665-f405793a-b39c-4197-af70-3471bb4f1b78.png)

**Comment by phaselden** [comment]
Hi Alex, the set of sities in the database is fairly limited ATM. Try Calcutta, or maybe Kolkata if that doesn't work. Add it to the list then you can edit it's name to be Delhi or whatever you want. (I am assuming here that they are all in the same timezone and have the same DST rules)

**Comment by alexjamesbrown** [comment]
Perfect, thanks
