### ISSUE TITLE
blank screen windows7 issue

### ISSUE THREAD

**Issue by nshopik** [phaselden/FlipIt#3]
Just replaced beta 1 with beta 2 and got just blank screen, settings seems works, but not screensaver itself

**Comment by phaselden** [comment]
Sorry to hear that. 
What OS are you using?

**Comment by nshopik** [comment]
Windows7 x64. I tried to mess around in settings maybe some of it cause problem with no luck

**Comment by phaselden** [comment]
Hmm, I don't have any Win7 machines to test that out, only Win 10. Are you able to debug the source to try and work out what is going on?

**Comment by nshopik** [comment]
Yeah i don't really know C# that well but my simplified glance didn't found anything suspicions, you basically packed font that's it. 

Beta 4 now show me one square (where hour is) instead fully blank black screen.

**Comment by phaselden** [comment]
The font it uses is now embedded, so that shouldn't be the problem. 

A couple of questions...

What's the make and model of the monitor (or laptop) you are using?

What is the screen resolution?

**Comment by nshopik** [comment]
dell 24' with 1920x1200. But i even tried todo clean VM install with windows7 just in case my installation is kinda funky, with same result. Also i did check originally i didn't had 4.8 framework but only 4.5, but upgrading didn't change thing.

**Comment by phaselden** [comment]
Hmm, that screen should be fine. 

Can you post a screenshot of what you see? (While it's running hit the PtSc key to copy the screen to the clipboard.)

**Comment by phaselden** [comment]
A question for others? If you are running Windows 7 are you also having problems?

**Comment by nshopik** [comment]
so i did additional test with windows 8.1, everything works fine. so seems to me its somehow windows7 only issue.
here is screen
![image](https://user-images.githubusercontent.com/4439311/106120509-84a71400-6167-11eb-9c32-e2e5229d83c3.png)

**Comment by moliuluo** [comment]
I encountered the same problem in the latest version

**Comment by redburn** [comment]
> A question for others? If you are running Windows 7 are you also having problems?

I see the same on a Windows 7 laptop. .NET Framework 4.8 is installed.

**Comment by phaselden** [comment]
OK thanks. I will try and find a Windows 7 machine to test it on, or read up on any differences in the Windows/.NET APIs which may be responsible.

**Comment by SmilerRyan** [comment]
> A question for others? If you are running Windows 7 are you also having problems?

I believe I see the same issue on a Windows 7 machine.
The machine has all the updates (apart from the language packs) installed.
It's runtimes are [The Visual C++ Redistributable Runtimes](https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/) and .NET Framework 4.8.

> Can you post a screenshot of what you see? (While it's running hit the PtSc key to copy the screen to the clipboard.)

<p float="left">
<image width="384" src="https://user-images.githubusercontent.com/14893385/106876974-326a7380-66d0-11eb-9562-fadd324c93d8.png">
<image width="384" src="https://user-images.githubusercontent.com/14893385/106875982-292cd700-66cf-11eb-93ac-578e6f65cf6e.png">
</p>

**Comment by JavaSCU** [comment]
same issue on a Windows 7 64bit, 1920x1080, HP EliteBook 820 G3, Version 1.2

**Comment by phaselden** [comment]
Thanks all. Those screenshots are helpful. It seems it is drawing the background of the first box, and then failing to draw the text (the hours) on top of it.

Can someone please check what happens if:
a) change to 24hr time if currently showing 12hr time, or visa versa?
b) display the World Times on the screen rather than the current time?

**Comment by redburn** [comment]
> a) change to 24hr time if currently showing 12hr time, or visa versa?
No difference there.

> b) display the World Times on the screen rather than the current time?
Like in clock mode, only the first flap is drawn for the World Times, so that seems to support your theory.

**Comment by nshopik** [comment]
> Support for OpenType fonts might be limited in Windows 7.

wasn't previous font (external) was also OpenType, no?

**Comment by redburn** [comment]
> wasn't previous font (external) was also OpenType, no?

The font wasn't included with FlipIt, the readme pointed to Google Fonts, where you can only download the TTF for Oswald.

I just installed the Oswald Bold OTF on Windows 7, and the screensaver (version 1.1) would not use it. Once I replaced it with the TTF, it worked. Not sure if that relates directly to the issue at hand, but a quick Google search turned up quite a few results regarding Windows 7 and OTF compatibility issues.

**Comment by phaselden** [comment]
Good news. I managed to track down what the issue was. It seems that under Windows 7 that the PrivateFontCollection class does not handle OTF fonts as well as Windows 10 does. The embedded fonts have been converted to TTF format (using https://everythingfonts.com/otf-to-ttf) and things seem to be working better now. A new release will be available soon.

**Comment by redburn** [comment]
Yep, that fixed it! Thanks.

**Comment by SmilerRyan** [comment]
Can also confirm that it runs fine on my Windows 7 Environment.
