### ISSUE TITLE
Proper Positioning on Vertical Monitors

### ISSUE THREAD

**Issue by kjsb25** [phaselden/FlipIt#4]
On my vertical monitor, the clock alignment isn't quite where I believe it should be. The current time clock is zoomed in much too far to see the full time, and the World clock is only a tad un-centered. 

Windows 10, Dell S2716DG, 1440x2560

Great project, appreciate ya greatly :)

**Comment by redburn** [comment]
Can you post a screenshot?

**Comment by phaselden** [comment]
Thanks @kjsb25. I rotated one of my monitors and can recreate the issue. I am planning on started to revise how the "current time" display is drawn today, so will make sure this is addressed as part of those changes.

**Comment by phaselden** [comment]
@kjsb25 - Beta 3 of v1.2 addresses the issue of the current time clock not drawing correctly in portrait mode.

**Comment by phaselden** [comment]
The next build addresses the positioning on the WorldTimes screen.
