### ISSUE TITLE
Optimized for vertical display

### ISSUE THREAD

**Issue by byerose** [phaselden/FlipIt#45]
On vertical display, due to the width it's so small.

**Comment by SmilerRyan** [comment]
I don't personally have a vertical monitor but I can see why it would be good to have.

Here's how it currently looks at the maximum size on a vertical monitor currently:
![1](https://user-images.githubusercontent.com/14893385/204377505-32b8d2fe-a7ad-4f4a-9da3-1eca4c829065.jpg)

I'd assume that we'd add an option to show each box separately, something like this:
![2](https://user-images.githubusercontent.com/14893385/204377826-a1b97494-5fc4-49d8-8960-a1b9cd3529ca.jpg)

**Comment by byerose** [comment]
> I don't personally have a vertical monitor but I can see why it would be good to have.
> 
> Here's how it currently looks at the maximum size on a vertical monitor currently: ![1](https://user-images.githubusercontent.com/14893385/204377505-32b8d2fe-a7ad-4f4a-9da3-1eca4c829065.jpg)
> 
> I'd assume that we'd add an option to show each box separately, something like this: ![2](https://user-images.githubusercontent.com/14893385/204377826-a1b97494-5fc4-49d8-8960-a1b9cd3529ca.jpg)

What you design is similar with fliplo. It's great.
![image](https://user-images.githubusercontent.com/81293778/204407451-e726850d-e6c1-417a-84a3-c1d0db030c89.png)
