### ISSUE TITLE
Windows Defender blocks 1.2 Beta 2 (Behavior:Win32/Execution.UE!ml)

### ISSUE THREAD

**Issue by redburn** [phaselden/FlipIt#5]
Windows Defender deleted the Version 1.2 Beta 2 .scr file because it detected a threat called Behavior:Win32/Execution.UE!ml.

Something about the recent changes is deemed "suspicious". I can submit it as a false alarm, but perhaps it can be avoided?

**Comment by redburn** [comment]
Doesn't come up in the [VirusTotal results](https://www.virustotal.com/gui/file/29037a1d0bce4e40d8cd5c1b91ba8f645b7027f7437b88f5b150567a89742570/detection), but it did for me on Windows 10. I've submitted it to Microsoft as an incorrect detection just now.

**Comment by redburn** [comment]
The analysis was completed, and Microsoft has removed the detection.

Hope it won't bother anyone else now.

**Comment by phaselden** [comment]
Excellent! Thanks Rob!
