### ISSUE TITLE
Unhandled exception when exiting screensaver (Version 1.2 Beta 3)

### ISSUE THREAD

**Issue by SnailMango** [phaselden/FlipIt#6]
Hi, I'm having problem with the new Version 1.2 Beta 3 after moving the mouse for exiting the screensaver.
Here's the complete error I get in the "Unhandled exception has occurred in your application" window:
(language is italian)

> Le informazioni su come richiamare il debug JIT (Just-In-Time) anziché questa finestra
> sono riportate in fondo al messaggio.
> 
> ************** Testo dell'eccezione **************
> System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
>    in ScreenSaver.MainForm.MainForm_FormClosed(Object sender, FormClosedEventArgs e)
>    in System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
>    in System.Windows.Forms.Form.RaiseFormClosedOnAppExit()
>    in System.Windows.Forms.Application.ExitInternal()
>    in System.Windows.Forms.Application.Exit(CancelEventArgs e)
>    in ScreenSaver.MainForm.MainForm_MouseMove(Object sender, MouseEventArgs e)
>    in System.Windows.Forms.Control.OnMouseMove(MouseEventArgs e)
>    in System.Windows.Forms.Control.WmMouseMove(Message& m)
>    in System.Windows.Forms.Control.WndProc(Message& m)
>    in System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    in System.Windows.Forms.Form.WndProc(Message& m)
>    in System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    in System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Assembly caricati **************
> mscorlib
>     Versione assembly: 4.0.0.0
>     Versione Win32: 4.8.4300.0 built by: NET48REL1LAST_C
>     Base di codice: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ----------------------------------------
> FlipIt
>     Versione assembly: 1.2.3.3438
>     Versione Win32: 1.2.3
>     Base di codice: file:///C:/WINDOWS/SysWOW64/FlipIt.scr
> ----------------------------------------
> System.Windows.Forms
>     Versione assembly: 4.0.0.0
>     Versione Win32: 4.8.4270.0 built by: NET48REL1LAST_C
>     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>     Versione assembly: 4.0.0.0
>     Versione Win32: 4.8.4300.0 built by: NET48REL1LAST_C
>     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Versione assembly: 4.0.0.0
>     Versione Win32: 4.8.4084.0 built by: NET48REL1
>     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Core
>     Versione assembly: 4.0.0.0
>     Versione Win32: 4.8.4300.0 built by: NET48REL1LAST_C
>     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Configuration
>     Versione assembly: 4.0.0.0
>     Versione Win32: 4.8.4190.0 built by: NET48REL1LAST_B
>     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Xml
>     Versione assembly: 4.0.0.0
>     Versione Win32: 4.8.4084.0 built by: NET48REL1
>     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> mscorlib.resources
>     Versione assembly: 4.0.0.0
>     Versione Win32: 4.8.4084.0 built by: NET48REL1
>     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_it_b77a5c561934e089/mscorlib.resources.dll
> ----------------------------------------
> System.Windows.Forms.resources
>     Versione assembly: 4.0.0.0
>     Versione Win32: 4.8.4084.0 built by: NET48REL1
>     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_it_b77a5c561934e089/System.Windows.Forms.resources.dll
> ----------------------------------------
> 
> ************** Debug JIT **************
> Per abilitare il debug JIT, è necessario impostare il valore
> jitDebugging nella sezione system.windows.forms del file di configurazione
> dell'applicazione o del computer (machine.config).
> L'applicazione inoltre deve essere compilata con il debug
> abilitato.
> 
> Ad esempio:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> Quando il debug JIT è abilitato, tutte le eccezioni non gestite
> vengono inviate al debugger JIT registrato nel computer,
> anziché essere gestite da questa finestra di dialogo.

![Immagine](https://user-images.githubusercontent.com/64862343/105606087-94a1ab00-5d97-11eb-80a6-5552cd230c39.jpg)

**Comment by phaselden** [comment]
Thanks @SnailMango and sorry about that. I am not quite sure why this is happening ATM but I have added a null check to (hopefully) avoid this issue. The beta 3 release has been updated with a new .scr file. Please try this and let me know how you go. (It's 3am here in Australia, so probably won't respond to any messages for a few hours)

**Comment by SnailMango** [comment]
I tried downloading the latest updated release but somehow now Windows Defender recognize the FlipIt.scr file as a trojan
![Immagine](https://user-images.githubusercontent.com/64862343/105613950-098bd980-5dc6-11eb-87cf-09293f09d289.jpg)

**Comment by redburn** [comment]
@SnailMango I've submitted it to Microsoft as a false positive, hope it will be cleared soon.

This is the [second time](https://github.com/phaselden/FlipIt/issues/5) a virus warning was triggered. I wonder what it is about the code that they don't like.

**Comment by phaselden** [comment]
Thanks again @redburn. I may start submitting the file before releasing it in future. 

It would be nice to know what is triggering it in the code though. Maybe it's the Win32 api calls I added recently to handle saving settings.

**Comment by redburn** [comment]
It was cleared. You may have to force an update of virus definitions for it to take immediate effect.
