### ISSUE TITLE
Can't add Norwegian cities

### ISSUE THREAD

**Issue by explor202** [phaselden/FlipIt#8]
Just found this clock today and love the world clock option. However, I noticed that I can't add any Norwegian cities to it, having tried Oslo, Lillehammer and a few others. I am using just the .scr file, but I don't think that would matter. Other European cities were added without an issue.

**Comment by phaselden** [comment]
The way I get the cities is by attempting to parse them out of the timezone's display name. Unfortunately this provides an inadequate list of city names. For example, there are no US or Canadian cities named in the original data, so after parsing out what is there I manually add in some US and Canadian ones.

According to https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-time-zones, Norway falls under W. Europe Standard Time and MS's list of cities for this is: Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna.
So what you could do, until I have a better solution, is add one of those cities to your list, then edit it's name to be whatever you want.

**Comment by explor202** [comment]
That's an excellent workaround. Thanks for it and the great screensaver!

**Comment by phaselden** [comment]
FYI - The next build includes more cities. Oslo is one of them.

**Comment by explor202** [comment]
Great, thanks!
